In [1]:
from tensorflow import keras
!pip3 install opencv-python
import cv2
import os
import numpy as np
!pip3 install pandas
import pandas as pd
!pip3 install matplotlib
import matplotlib.pyplot as plt # for data visualization purposes
!pip3 install seaborn
import seaborn as sns # for statistical data visualization
!pip3 install sklearn
from sklearn.naive_bayes import MultinomialNB
%matplotlib inline

In [2]:
dataset = np.load('mnist.npz')
lst = dataset.files
data = []
for item in lst:
#     print(item)
#     print(dataset[item])
    data.append(dataset[item])
    
x_test = data[0]
x_train = data[1]
y_train = data[2]
y_test = data[3]

x_test = np.array(x_test)
x_train = np.array(x_train)
y_train = np.array(y_train)
y_test = np.array(y_test)
x_test.shape
# (X_raw_train, y_train), (X_raw_test, y_test) = dataset.load_data()


(10000, 28, 28)

In [3]:
clf = MultinomialNB()

In [4]:
num,x,y = x_test.shape
x_test = x_test.reshape(num,x*y)
x_test.shape

(10000, 784)

In [5]:
x_train.shape

(60000, 28, 28)

In [6]:
num,x,y = x_train.shape
x_train = x_train.reshape(num,x*y)

In [7]:
x_train.shape

(60000, 784)

In [8]:
y_test.shape

(10000,)

In [9]:
y_train.shape

(60000,)

In [10]:
clf.fit(x_train,y_train)

MultinomialNB()

In [11]:
x_test.shape

(10000, 784)

In [12]:
y_pred = clf.predict(x_test)

In [13]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(matrix)
c_r = classification_report(y_test, y_pred)
print("Classification Report:")
print (c_r)
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)


Confusion Matrix:
[[ 912    0    2    6    1    8   14    1   36    0]
 [   0 1061    5    9    0    2    6    0   51    1]
 [  15   11  858   24   10    3   33   11   66    1]
 [   4   11   34  851    1   21    7   14   40   27]
 [   2    2    6    0  732    0   25    1   38  176]
 [  23   11    6  107   18  590   17    6   78   36]
 [  17   13   17    1    7   25  860    0   18    0]
 [   1   21   11    5   19    0    1  861   40   69]
 [   6   26   13   54   14   27    8    9  777   40]
 [   6    7    3   10   66   10    0   17   27  863]]
Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.93      0.93       980
           1       0.91      0.93      0.92      1135
           2       0.90      0.83      0.86      1032
           3       0.80      0.84      0.82      1010
           4       0.84      0.75      0.79       982
           5       0.86      0.66      0.75       892
           6       0.89      0.90      0.89     

In [14]:
def feature_selection(x_train,y_train,x_test,y_test,features,score):
    clf = MultinomialNB()
    score2 = 0
    scores = []
    if len(features)>23:
        return features
    if len(features)==0:
        for i in range(x_train.shape[1]):
            data=[]
            data = x_train[:,[i]]
            test = x_test[:,[i]]
            clf.fit(data,y_train)
            y_pred = clf.predict(test)
            score2 = accuracy_score(y_test,y_pred)
            scores.append(score2)
    

        score2 = max(scores)
        index = scores.index(score2)
        features.append(index)
        if score2>score:
            score = score2
            feature_selection(x_train,y_train,x_test,y_test,features,score)
        else:
            if score2>score-0.07 and score2<score+0.07 :
                score = score2
                feature_selection(x_train,y_train,x_test,y_test,features,score)
            else:
                                
                return features
                


    else:

#         print(len(data))
#         print(x_train.shape)
#         print(1)
        data = np.zeros((x_train.shape[0],1))
        test = np.zeros((x_test.shape[0],1))
        a=0
        test = np.array(test)
        for i in features:
            if a==0:
                data = x_train[:,[i]]
                test = x_test[:,[i]]
                a = a+1
            else:
                data = np.append(data,x_train[:,[i]],axis = 1)
                test = np.append(test,x_test[:,[i]],axis = 1)


        x_train = np.delete(x_train,features[-1],axis = 1)

        for j in range(0,x_train.shape[1]):
#             a = a+1
#             print(a)
            data = np.append(data,x_train[:,j].reshape(-1,1),axis=1)
            clf.fit(data,y_train)
            test = np.append(test,x_test[:,j].reshape(-1,1),axis=1)
            y_pred = clf.predict(test)
            score2 = accuracy_score(y_test,y_pred)
            scores.append(score2)
            data = np.delete(data,-1,axis=1)
            test = np.delete(test,-1,axis=1)

        score2 = max(scores)
        index = scores.index(score2)
        features.append(index)
        if len(features)==784:
            return features
        else:
            if score2>score:
                score = score2
                feature_selection(x_train,y_train,x_test,y_test,features,score)
            else:
                if score2>score-0.07 and score2<score+0.07:
                    score = score2
                    feature_selection(x_train,y_train,x_test,y_test,features,score)
                else:
                                
                    return features
    
            
        
        
        
        
        


In [15]:

features = []
score = 0
x_train_new = np.copy(x_train)
x_test_new = np.copy(x_test)
feature_selection(x_train_new,y_train,x_test_new,y_test,features,score)

        

In [16]:
data = np.zeros((x_train.shape[0],1))
test = np.zeros((x_test.shape[0],1))
a=0
test = np.array(test)
for i in features:
    if a==0:
        data = x_train[:,[i]]
        test = x_test[:,[i]]
        a = a+1
    else:
        data = np.append(data,x_train[:,[i]],axis = 1)
        test = np.append(test,x_test[:,[i]],axis = 1)

In [17]:
clf = MultinomialNB()
clf.fit(data,y_train)
y_pred = clf.predict(test)

matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(matrix)
c_r = classification_report(y_test, y_pred)
print("Classification Report:")
print (c_r)
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)


Confusion Matrix:
[[ 762    0   13   81   15   27   45   10   15   12]
 [   1 1028   15   23    8    0    3   16   40    1]
 [  37   80  564   54   45   16  121   17   76   22]
 [  21   10   33  742   11   55    7   57   63   11]
 [  11    4   18   17  460   11  112   64   26  259]
 [  36   33   33  205   34  446   25   32   43    5]
 [  49   20   41    3   63   22  723    6    7   24]
 [  17   27   17   33   29    7   25  747   66   60]
 [  14   99  134   63   21   49   20   50  505   19]
 [  13   17    8   24  122    6   27  231   17  544]]
Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.78      0.79       980
           1       0.78      0.91      0.84      1135
           2       0.64      0.55      0.59      1032
           3       0.60      0.73      0.66      1010
           4       0.57      0.47      0.51       982
           5       0.70      0.50      0.58       892
           6       0.65      0.75      0.70     

In [18]:
print(features)

[0, 410, 468, 301, 150, 581, 189, 354, 475, 128, 247, 354, 206, 365, 156, 414, 465, 516, 382, 459, 655, 255, 428, 625]
